<?xml version="1.0" encoding="iso-8859-1" standalone="yes"?>


<!DOCTYPE ndr (ndrrenseignements*)[

<!ELEMENT ndrrenseignements (ndrmatricule,ndrnom,ndrprenoms,ndrage,ndrsexe,ndrtaille,ndrformation,ndrniveauetude,ndrstatut,ndrhabitation,)>

<!ELEMENT ndrmatricule (#PCDATA)>
<!ELEMENT ndrnom (#PCDATA)>
<!ELEMENT ndrprenoms (#PCDATA)>
<!ELEMENT ndrage (#PCDATA)>
<!ELEMENT ndrsexe (H | F) "F">
<!ELEMENT ndrtaille (#PCDATA)>
<!ELEMENT ndrformation (#PCDATA)>
<!ELEMENT ndrniveauetude (#PCDATA)>
<!ELEMENT ndrstatut (#PCDATA)>
<!ELEMENT ndrhabitation (#PCDATA)>
]>

<ndr>
   <ndrmatricule>004404N</ndrmatricule>
   <ndrnom>N'dri</ndrnom>
   <ndrprenoms>Konan Akissi Francine Epouse Brou</ndrprenoms>
   <ndrage>25 ans</ndrage>
   <ndrsexe>Feminin</ndrsexe>
   <ndrtaille>155m</ndrtaille>
   <ndrformation>informatique developpeur d'applications</ndrformation>
   <ndrniveauetude>bac+2</ndrniveauetude>
   <ndrstatut>mari√©e</ndrstatut>
   <ndrhabitation>yopougon</ndrhabitation>
</ndr>


